### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by Diwakar-Gupta** [Diwakar-Gupta/pepper#1]
- [x] support test cases in public repository
- [x] enable `Submit` feature judge will download test cases for that code and execute
- [x] store code and result in sqlite.db.
- [x] enable feature to see what all questions i have solved in past
- [x] see submission history for a given problem.
- [x] judge will create a random code for connection, and a link when opened frontend will use that code to connect
- [x] judge setup, create run_judge as a file tracked by git.
